[package]
name = "gitkeep"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gitkeep"
path = "src/rust/main.rs"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
walkdir = "2.5.0"
